package haven;

import java.util.HashMap;
import java.util.Map;

public class CurioStudyTimes {
    public final static Map<String, Double> curios = new HashMap<String, Double>(76) {{
        put("ants-empress", 3 + 20.0 / 60.0);
        put("ants-queen", 1 + 20.0 / 60.0);
        put("ants-soldiers", 40.0 / 60.0);
        put("aurochshair", 48.0);
        put("barkboat", 4.0);
        put("beartooth", 30.0);
        put("bloatedbolete", 8.0);
        put("boartusk", 12.0);
        put("catgold", 20.0);
        put("chimingbluebell", 18.0);
        put("conecow", 20.0 / 60.0);
        put("dandelion", 40.0 / 60.0);
        put("darkheart", 96.0);
        put("ladysmantledew", 5.0);
        put("batwings", 4.0);
        put("deathchrysalis", 9.0);
        put("dragonfly-emerald", 4.0);
        put("enthronedtoad", 48.0);
        put("everglowingember", 38.0);
        put("featherduster", 8.3);
        put("feathertrinket", 2.0);
        put("fishyeyeball", 8.0);
        put("fourleafclover", 10.0);
        put("frogscrown", 8.0);
        put("glimmermoss", 5.0);
        put("luckyrabbits-dry", 24.0);
        put("horribleknot", 16.0);
        put("itsybitsyspider", 32.0);
        put("itsybitsysweb", 38.0);
        put("ladysmantle", 5.0);
        put("ladybug", 4.0);
        put("squirreltail", 42.0);
        put("leatherball", 48.0);
        put("mirkwoodoffering", 2.0);
        put("oddtuber", 16.0);
        put("bronzesteed", 34.0);
        put("flotsam", 4.0);
        put("petrifiedshell", 60.0);
        put("flower-poppy", 15.0);
        put("primitivedoll", 14.5);
        put("prism", 12.0);
        put("rattletattle", 36.0);
        put("antlers-reddeer", 50.0);
        put("riverpearl", 1.0);
        put("bouquet", 16.0 + 40.0 / 60.0);
        put("royaltoadstool", 6.0);
        put("dragonfly-ruby", 4.0);
        put("volvawand", 10.0);
        put("seersbones", 2.0);
        put("seersbowl", 8.0);
        put("seerstea", 24.0);
        put("silkenribbon", 15.0);
        put("crudeidol", 9.0);
        put("stalagoom", 3.0);
        put("stillife", 4.5);
        put("strangecrystal", 60.0);
        put("strawdoll", 4.0);
        put("tangledbramble", 9.5);
        put("ernst", 20.5);
        put("thornythistle", 5.5);
        put("tinwarrior", 24.0);
        put("tinyabacus", 16.0);
        put("toychariot", 24.0);
        put("snapdragon", 14.5);
        put("bladderwrack", 8.0);
        put("wishbone", 24.0);
        put("wondrouswoodshaving", 72.0);
        put("ivoryfigurine", 9.0);
        put("silverrose", 22.0);
        put("goldentooth", 34.0);
        put("greatwaxseal", 9.0);
        put("antfarm", 8.0);
        put("seersspindle", 16.0);
        put("edelweiss", 29.0);
        put("wormapple", 11.0);
        put("motherofpearl", 1.2);
    }};
}
